/// <reference types="../../../types/index.d.ts" />
/**
 * This file is automatically generated. Do not make any manual modifications.
 */

/**
* Inputs to the Grasshopper component.
*/
interface Inputs {
/**
    * The first value to sum
    */
a?: number;
/**
    * The second value to sum
    */
b?: number;
}

/**
* Outputs from the Grasshopper component.
*/
interface Outputs {
/**
    * The result of a + b
    */
x?: number;
}

/**
 * The context in which the Grasshopper component is executed.
 */
interface Context {
  /**
   * The active Rhino Document
   */
  RhinoDocument: InstanceType<typeof import("node-api-dotnet").Rhino.RhinoDoc>;
  /**
   * The active Grasshopper document
   */
  GrasshopperDocument: InstanceType<typeof import("node-api-dotnet").Grasshopper.Kernel.GH_Document>;
  /**
   * The Grasshopper component executing this script
   */
  Component: InstanceType<typeof import("node-api-dotnet").Grasshopper.Kernel.GH_Component>;
}
