/// This file is automatically generated. Do not make any manual modifications.
/// <reference types="../../../types/index.d.ts" />

/**
 * Inputs to the Grasshopper component.
 */
type Inputs = {
  /**
   * The first value to sum
   */
  a?: number;
  /**
   * The second value to sum
   */
  b?: number;
}

/**
* Outputs from the Grasshopper component.
*/
type Outputs = {
  /**
   * The result of a + b
   */
  x?: number;
}

/**
 * The context in which the Grasshopper component is executed.
 */
type Context = {
  /**
   * The active Rhino Document
   */
  RhinoDocument: InstanceType<typeof dotnet.Rhino.RhinoDoc>;
  /**
   * The active Grasshopper document
   */
  GrasshopperDocument: InstanceType<typeof dotnet.Grasshopper.Kernel.GH_Document>;
  /**
   * The Grasshopper component executing this script
   */
  Component: InstanceType<typeof dotnet.Grasshopper.Kernel.GH_Component>;
}
