/**
 * This file is automatically generated. Do not make any manual modifications.
 */

namespace Component {
  /**
   * Inputs to the Grasshopper component.
   */
  interface Inputs {
    /**
     * The first value to sum
     */
    a: number;
    /**
     * The second value to sum
     */
    b: number;
  }

  /**
   * Outputs from the Grasshopper component.
   */
  interface Outputs {
    /**
     * The result of a + b
     */
    sum: number;
  }
}
